name: Package Server

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  package-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build the server
        run: yarn build:server
      - name: Zip the server
        run: |
          mkdir -p sync-server
          cp package.json sync-server
          cp -r .yarn sync-server
          cp yarn.lock sync-server
          cp .yarnrc.yml sync-server
          cp .yarnrc.yml sync-server
          cp packages/sync-server/package.json sync-server
          cp packages/sync-server/app.js sync-server
          cp -r packages/sync-server/src sync-server
          cp -r packages/sync-server/migrations sync-server
          cp -r packages/sync-server/web-client sync-server
          zip -r sync-server.zip sync-server
      - name: Upload Server with Client Build
        uses: actions/upload-artifact@v4
        with:
          name: sync-server
          include-hidden-files: true
          path: sync-server.zip
      - name: List
        run: ls -la
      - name: Add to Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: sync-server.zip
