name: Package Server

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  package-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build the server
        run: yarn build:server
      - name: Create dist folder
        run: |
          mkdir -p dist
          cp -r packages/sync-server/package.json dist
          cp -r packages/sync-server/yarn.lock dist
          cp -r packages/sync-server/.yarn dist
          cp -r packages/sync-server/.yarnrc.yml dist
          cp -r packages/sync-server/app.js dist
          cp -r packages/sync-server/src dist
          cp -r packages/sync-server/migrations dist
          cp -r packages/sync-server/web-client dist
      - name: Upload Server with Client Build
        uses: actions/upload-artifact@v4
        with:
          name: sync-server
          path: dist
