name: Package Server

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  package-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build the server
        run: yarn build:server
      - name: List files
        run: la -la
      - name: Upload Server with Client Build
        uses: actions/upload-artifact@v4
        include-hidden-files: true
        with:
          name: sync-server
          path: |
            package.json
            yarn.lock
            .yarn
            .yarnrc.yml
            packages/sync-server/package.json
            packages/sync-server/app.js
            packages/sync-server/src
            packages/sync-server/migrations
            packages/sync-server/web-client
