name: Publish npm packages

# # Npm packages are published for every new tag
# on:
#   push:
#     tags:
#       - 'v*.*.*'

# DELETE ME
on:
  pull_request:
# DELETE ME

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish npm packages
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Build Web
        run: yarn build:browser

      - name: publish web
        run: |
          # Publish the packages
          # The publish command will automatically detect the version from the tag
          # and publish the packages to the npm registry
          # The --access public flag is required for scoped packages
          yarn workspace @actual-app/web npm publish --access public

      - name: publish sync-server
        run: |
          # Publish the packages
          # The publish command will automatically detect the version from the tag
          # and publish the packages to the npm registry
          # The --access public flag is required for scoped packages
          yarn workspace @actual-app/sync-server npm publish --access public
