name: Publish npm packages

# # Npm packages are published for every new tag
# on:
#   push:
#     tags:
#       - 'v*.*.*'

# DELETE ME
on:
  pull_request:
# DELETE ME

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    name: Build and publish npm packages
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Build Web
        run: yarn build:browser

      - name: Pack the web package
        run: |
          # Pack the packages
          # The pack command will create a .tgz file for each package in the packages directory
          yarn workspace @actual-app/web pack --filename @actual-app/web.tgz
          yarn workspace @actual-app/sync-server pack --filename @actual-app/sync-server.tgz

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            packages/desktop-client/@actual-app/web.tgz
            packages/sync-server/@actual-app/sync-server.tgz

  publish:
    runs-on: ubuntu-latest
    name: Publish npm packages
    needs: build-and-pack
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup node and npm registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # registry-url: 'https://registry.npmjs.org'
          # delete the below
          registry-url: 'https://npm.pkg.github.com'
          scope: '@octocat'
          # delete the above

      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages

      - name: Publish Web
        run: |
          # Publish the packages
          # The publish command will automatically detect the version from the tag
          # and publish the packages to the npm registry
          # The --access public flag is required for scoped packages
          npm publish desktop-client/@actual-app/web.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Sync-Server
        run: |
          # Publish the packages
          # The publish command will automatically detect the version from the tag
          # and publish the packages to the npm registry
          # The --access public flag is required for scoped packages
          npm publish sync-server/@actual-app/sync-server.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
